### ISSUE TITLE
Replace use of mem::uninitialized in switch_left

### ISSUE THREAD

**Issue by ghost** [makoConstruct/jostletree.rs#2]
Hello! In https://github.com/rust-lang/rust/pull/99389 we're making the checks for mem::uninitialized stricter, and this crate came up as an issue.

The use of uninitialized here is unsound, but can be pretty easily fixed either by using swap_nonoverlapping, or MaybeUninit for temporary space.

**Comment by makoConstruct** [comment]
I'll go with MaybeUninit. If I use swaps, it might end up doing six writes to three different parts of memory? while this only needs to do three. Probably wont be faster in most cases, but could be!

**Comment by ghost** [comment]
> If I use swaps, it might end up doing six writes to three different parts of memory?

Well, I'd assume the compiler would be able to optimise out the redundant swaps. Though I've not tested that, it feels like the kind of thing it will do.

In any case, this fixes it :) Thank you!
